spring.application.name: core-api
spring.profiles.active: local-dev

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - logging.yml
      - db-core.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
jwt:
  secret: ${JWT_SECRET:default_secret_key_here} # .env의 값을 읽거나 기본값 사용
  expiration-seconds: 36000
  issuer: "nexsol-admin"
external:
  memo-service:
    url: ${MEMO_SERVICE_URL}
---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev
spring:
  jmx:
    enabled: false
---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live

